import User from '../models/User.js';
import Vehicle from '../models/Vehicle.js';
import Location from '../models/Location.js';
import Review from '../models/Review.js';

const initialLocations = [
  { name: 'Panaji', address: 'MG Road, Panaji, Goa', latitude: 15.4989, longitude: 73.8278 },
  { name: 'Calangute', address: 'Main Beach Road, Calangute, Goa', latitude: 15.5438, longitude: 73.7554 },
  { name: 'Baga', address: 'Tito Lane End, Baga, Goa', latitude: 15.5553, longitude: 73.7517 },
  { name: 'Anjuna', address: 'Flea Market Road, Anjuna, Goa', latitude: 15.5847, longitude: 73.7439 },
  { name: 'Vagator', address: 'Ozran Beach Path, Vagator, Goa', latitude: 15.6028, longitude: 73.7381 },
  { name: 'Mapusa', address: 'Bus Stand Circle, Mapusa, Goa', latitude: 15.5925, longitude: 73.8167 },
  { name: 'Margao', address: 'Railway Station Road, Margao, Goa', latitude: 15.2736, longitude: 73.9582 },
  { name: 'Vasco', address: 'Airport Road, Vasco da Gama, Goa', latitude: 15.3949, longitude: 73.8153 },
  { name: 'Dabolim Airport', address: 'Arrival Terminal 1, Dabolim Airport, Goa', latitude: 15.3808, longitude: 73.8314 },
];

const initialVehicles = [
  {
    name: 'Honda Activa 6G',
    brand: 'Honda',
    model: '6G Standard',
    type: 'bike',
    category: 'Scooter',
    description: 'Smooth, reliable automatic scooter perfect for exploring Goa beach lanes and quick city rides.',
    pricePerDay: 450,
    pricePerHour: 50,
    securityDeposit: 1000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    seats: '2 seats',
    mileage: '45 km/l',
    location: 'Calangute',
    image: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Honda_Activa_6G.jpg?width=1200',
    rating: 4.8,
    reviewCount: 34,
    features: ['Automatic Transmission', 'Helmet Included', 'Under-seat Storage', 'Eco Engine'],
  },
  {
    name: 'Royal Enfield Classic 350',
    brand: 'Royal Enfield',
    model: 'Classic 350 Chrome',
    type: 'bike',
    category: 'Cruiser',
    description: 'Iconic cruiser bike for an unforgettable Goan coastal road trip experience.',
    pricePerDay: 850,
    pricePerHour: 90,
    securityDeposit: 2000,
    fuelType: 'Petrol',
    transmission: 'Manual',
    seats: '2 seats',
    mileage: '35 km/l',
    location: 'Baga',
    image: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/2022Classic350.jpg?width=1200',
    rating: 4.9,
    reviewCount: 52,
    features: ['ABS Brakes', 'Cruiser Ergonomics', 'Dual Helmets', 'Luggage Carrier'],
  },
  {
    name: 'Yamaha R15 V4',
    brand: 'Yamaha',
    model: 'V4 Racing Blue',
    type: 'bike',
    category: 'Sports',
    description: 'High-performance sports bike for speed lovers wanting to ride along the scenic Goa highways.',
    pricePerDay: 1000,
    pricePerHour: 110,
    securityDeposit: 2500,
    fuelType: 'Petrol',
    transmission: 'Manual',
    seats: '2 seats',
    mileage: '40 km/l',
    location: 'Anjuna',
    image: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Yamaha_R15_v4_bike.jpg?width=1200',
    rating: 4.8,
    reviewCount: 28,
    features: ['Quick Shifter', 'Traction Control', 'LED Headlamp', 'Digital Console'],
  },
  {
    name: 'KTM Duke 390',
    brand: 'KTM',
    model: 'Duke 390 Orange',
    type: 'bike',
    category: 'Naked Sports',
    description: 'Raw power and agility for motorcycle enthusiasts exploring North and South Goa.',
    pricePerDay: 1200,
    pricePerHour: 130,
    securityDeposit: 3000,
    fuelType: 'Petrol',
    transmission: 'Manual',
    seats: '2 seats',
    mileage: '28 km/l',
    location: 'Vagator',
    image: 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&q=80&w=1000',
    rating: 4.9,
    reviewCount: 19,
    features: ['Ride by Wire', 'TFT Display', 'Cornering ABS', 'Slipper Clutch'],
  },
  {
    name: 'Royal Enfield Himalayan 450',
    brand: 'Royal Enfield',
    model: 'Himalayan 450',
    type: 'bike',
    category: 'Adventure',
    description: 'Adventure tourer designed for rough terrain, hinterland trips, and waterfalls in Goa.',
    pricePerDay: 1100,
    pricePerHour: 120,
    securityDeposit: 2500,
    fuelType: 'Petrol',
    transmission: 'Manual',
    seats: '2 seats',
    mileage: '30 km/l',
    location: 'Panaji',
    image: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&q=80&w=1000',
    rating: 4.8,
    reviewCount: 24,
    features: ['Long Travel Suspension', 'Tripper Navigation', 'Spoke Wheels', 'Dual ABS'],
  },
  {
    name: 'Suzuki Access 125',
    brand: 'Suzuki',
    model: 'Special Edition',
    type: 'bike',
    category: 'Scooter',
    description: 'Comfortable family scooter with great fuel efficiency and retro chrome mirrors.',
    pricePerDay: 480,
    pricePerHour: 55,
    securityDeposit: 1000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    seats: '2 seats',
    mileage: '48 km/l',
    location: 'Mapusa',
    image: 'https://images.unsplash.com/photo-1591637333184-19aa84b3e01f?auto=format&fit=crop&q=80&w=1000',
    rating: 4.7,
    reviewCount: 41,
    features: ['USB Charging', 'Bluetooth Connect', 'Large Boot Space', 'Led Lamp'],
  },
  {
    name: 'Bajaj Pulsar N250',
    brand: 'Bajaj',
    model: 'N250 Metallic',
    type: 'bike',
    category: 'Street',
    description: 'Responsive streetfighter bike for cruising through Panaji streets and highway tollways.',
    pricePerDay: 750,
    pricePerHour: 80,
    securityDeposit: 1500,
    fuelType: 'Petrol',
    transmission: 'Manual',
    seats: '2 seats',
    mileage: '38 km/l',
    location: 'Margao',
    image: 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&q=80&w=1000',
    rating: 4.6,
    reviewCount: 15,
    features: ['Assist Clutch', 'Infinity Display', 'Dual Channel ABS', 'Monoshock'],
  },
  {
    name: 'Mahindra Thar 4x4 Hardtop',
    brand: 'Mahindra',
    model: 'LX 4x4 Automatic',
    type: 'car',
    category: 'SUV 4x4',
    description: 'The ultimate Goa beach SUV. Dominating presence, open feel, and automatic 4x4 drive.',
    pricePerDay: 3500,
    pricePerHour: 350,
    securityDeposit: 5000,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    seats: '4 seats',
    mileage: '13 km/l',
    location: 'Calangute',
    image: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Mahindra_Thar.jpg?width=1200',
    rating: 4.9,
    reviewCount: 68,
    features: ['4x4 Drive', 'Convertible / Hardtop', 'Touchscreen Infotainment', 'Alloy Wheels'],
  },
  {
    name: 'Hyundai i20 Asta',
    brand: 'Hyundai',
    model: 'Asta Option Turbo',
    type: 'car',
    category: 'Hatchback',
    description: 'Premium hatchback with sunroof, Bose audio system, and easy parking in narrow streets.',
    pricePerDay: 1900,
    pricePerHour: 200,
    securityDeposit: 3000,
    fuelType: 'Petrol',
    transmission: 'Manual',
    seats: '5 seats',
    mileage: '18 km/l',
    location: 'Panaji',
    image: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/2020_Hyundai_i20_1.2_MPI_%28BC3%29.jpg?width=1200',
    rating: 4.7,
    reviewCount: 39,
    features: ['Electric Sunroof', 'Bose Sound System', 'Rear AC Vents', 'Wireless Charging'],
  },
  {
    name: 'Toyota Innova Crysta',
    brand: 'Toyota',
    model: '2.4 ZX 7-Seater',
    type: 'car',
    category: 'MUV',
    description: 'Unmatched luxury for family trips or group vacations across Goa beaches and airports.',
    pricePerDay: 3200,
    pricePerHour: 320,
    securityDeposit: 4000,
    fuelType: 'Diesel',
    transmission: 'Manual',
    seats: '7 seats',
    mileage: '14 km/l',
    location: 'Dabolim Airport',
    image: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Toyota_Innova.jpg?width=1200',
    rating: 4.9,
    reviewCount: 75,
    features: ['Captain Seats', 'Dual Climate Control', 'Leather Upholstery', 'Spacious Boot'],
  },
  {
    name: 'Hyundai Creta SX',
    brand: 'Hyundai',
    model: 'SX Executive',
    type: 'car',
    category: 'SUV',
    description: 'India’s most loved compact SUV. Panoramic sunroof and smooth ride quality.',
    pricePerDay: 2600,
    pricePerHour: 260,
    securityDeposit: 3500,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    seats: '5 seats',
    mileage: '16 km/l',
    location: 'Baga',
    image: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&q=80&w=1000',
    rating: 4.8,
    reviewCount: 45,
    features: ['Panoramic Sunroof', 'Ambient Lighting', 'Cruise Control', 'Push Button Start'],
  },
  {
    name: 'Tata Nexon EV Max',
    brand: 'Tata',
    model: 'EV Max Dark Edition',
    type: 'car',
    category: 'EV SUV',
    description: 'Eco-friendly electric SUV with 400km range per charge. Free charging at key Goa points.',
    pricePerDay: 2200,
    pricePerHour: 220,
    securityDeposit: 3000,
    fuelType: 'EV',
    transmission: 'Automatic',
    seats: '5 seats',
    mileage: '400 km/charge',
    location: 'Panaji',
    image: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&q=80&w=1000',
    rating: 4.8,
    reviewCount: 29,
    features: ['Silent Electric Drive', 'Fast Charging Compatible', 'Ventilated Seats', 'JBL Audio'],
  },
  {
    name: 'Kia Seltos GTX Plus',
    brand: 'Kia',
    model: 'GTX Plus DCT',
    type: 'car',
    category: 'SUV',
    description: 'Stylish SUV with head-up display, 360 camera, and sporty interior layout.',
    pricePerDay: 2800,
    pricePerHour: 280,
    securityDeposit: 4000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    seats: '5 seats',
    mileage: '15 km/l',
    location: 'Anjuna',
    image: 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&q=80&w=1000',
    rating: 4.9,
    reviewCount: 33,
    features: ['360 Degree Camera', 'Head-Up Display', 'Bose Speakers', 'Smart Air Purifier'],
  },
  {
    name: 'Jeep Compass Limited',
    brand: 'Jeep',
    model: 'Limited 4x4',
    type: 'car',
    category: 'Luxury SUV',
    description: 'American luxury SUV built for smooth highways and rugged waterfall excursions.',
    pricePerDay: 3800,
    pricePerHour: 380,
    securityDeposit: 5000,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    seats: '5 seats',
    mileage: '14 km/l',
    location: 'Vagator',
    image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=1000',
    rating: 4.9,
    reviewCount: 22,
    features: ['4x4 Select-Terrain', 'Dual-Pane Sunroof', 'Alpine Sound System', 'Power Tailgate'],
  },
  {
    name: 'Mahindra XUV700 AX7',
    brand: 'Mahindra',
    model: 'AX7 Luxury Pack',
    type: 'car',
    category: 'SUV 7-Seater',
    description: 'Flagship 7-seater SUV with ADAS safety features, panoramic Skyroof, and Sony 3D sound.',
    pricePerDay: 3600,
    pricePerHour: 360,
    securityDeposit: 5000,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    seats: '7 seats',
    mileage: '13 km/l',
    location: 'Margao',
    image: 'https://images.unsplash.com/photo-1609521263047-f8d205293f24?auto=format&fit=crop&q=80&w=1000',
    rating: 4.9,
    reviewCount: 40,
    features: ['Sony 3D Sound', 'ADAS Level 2', 'Skyroof', 'Flush Door Handles'],
  },
  {
    name: 'Maruti Swift ZXi',
    brand: 'Maruti',
    model: 'ZXi Dual Tone',
    type: 'car',
    category: 'Hatchback',
    description: 'Nimble, fuel-efficient hatchback favorite for easy maneuvering and budget travel.',
    pricePerDay: 1400,
    pricePerHour: 140,
    securityDeposit: 2000,
    fuelType: 'Petrol',
    transmission: 'Manual',
    seats: '5 seats',
    mileage: '22 km/l',
    location: 'Vasco',
    image: 'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&q=80&w=1000',
    rating: 4.7,
    reviewCount: 56,
    features: ['Fuel Efficient', 'Touchscreen Audio', 'Automatic Climate Control', 'Dual Airbags'],
  },
  {
    name: 'Maruti Baleno Alpha',
    brand: 'Maruti',
    model: 'Alpha Automatic',
    type: 'car',
    category: 'Hatchback',
    description: 'Spacious premium hatchback with HUD display, 360 view camera, and smooth automatic transmission.',
    pricePerDay: 1600,
    pricePerHour: 160,
    securityDeposit: 2500,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    seats: '5 seats',
    mileage: '20 km/l',
    location: 'Mapusa',
    image: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&q=80&w=1000',
    rating: 4.8,
    reviewCount: 31,
    features: ['360 Camera', 'Head Up Display', 'SmartPlay Pro+', 'Keyless Entry'],
  },
  {
    name: 'Volkswagen Virtus GT',
    brand: 'Volkswagen',
    model: 'GT 1.5 TSI DSG',
    type: 'car',
    category: 'Sedan',
    description: 'German performance sedan with 150HP turbo engine for refined highway touring.',
    pricePerDay: 2500,
    pricePerHour: 250,
    securityDeposit: 3500,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    seats: '5 seats',
    mileage: '16 km/l',
    location: 'Panaji',
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=1000',
    rating: 4.9,
    reviewCount: 27,
    features: ['1.5L TSI Engine', 'Paddle Shifters', 'Ventilated Front Seats', 'Digital Cockpit'],
  },
  {
    name: 'BMW 3 Series Gran Limousine',
    brand: 'BMW',
    model: '320ld M Sport',
    type: 'car',
    category: 'Luxury',
    description: 'Ultimate luxury sedan experience for weddings, executive trips, or luxury Goa vacations.',
    pricePerDay: 7500,
    pricePerHour: 800,
    securityDeposit: 10000,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    seats: '5 seats',
    mileage: '15 km/l',
    location: 'Dabolim Airport',
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&q=80&w=1000',
    rating: 5.0,
    reviewCount: 14,
    features: ['BMW Curved Display', 'Harman Kardon Sound', 'Panoramic Glass Roof', 'M Sport Package'],
  },
];

export const autoSeedIfEmpty = async () => {
  try {
    const existingVehicleCount = await Vehicle.countDocuments();
    if (existingVehicleCount > 0) {
      console.log(`ℹ️ MongoDB contains ${existingVehicleCount} existing vehicles. Skipping seed to preserve all user data.`);
      return;
    }

    console.log('🌱 Database is empty. Seeding initial GoaRide records into MongoDB...');

    await Location.insertMany(initialLocations);

    const adminUser = await User.create({
      name: 'GoaRide Admin',
      email: process.env.ADMIN_EMAIL || 'admin@goaride.com',
      phone: '+91 98765 43210',
      password: process.env.ADMIN_PASSWORD || 'admin123',
      role: 'ADMIN',
      profileImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=300',
    });

    const demoUser = await User.create({
      name: 'Rahul Sharma',
      email: 'user@goaride.com',
      phone: '+91 91234 56789',
      password: 'user123',
      role: 'USER',
      profileImage: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&q=80&w=300',
    });

    const vehiclesWithTrackingIds = initialVehicles.map((v, i) => ({
      ...v,
      trackingId: `TRK-890${i + 1}`,
    }));

    const createdVehicles = await Vehicle.insertMany(vehiclesWithTrackingIds);

    await Review.insertMany([
      {
        user: demoUser._id,
        vehicle: createdVehicles[0]._id,
        rating: 5,
        comment: 'Super easy pickup in Calangute! Scooter was in great condition with helmets.',
      },
      {
        user: demoUser._id,
        vehicle: createdVehicles[1]._id,
        rating: 5,
        comment: 'Riding the Classic 350 along Baga beach road was the highlight of our Goa trip!',
      },
      {
        user: demoUser._id,
        vehicle: createdVehicles[7]._id,
        rating: 5,
        comment: 'The Thar 4x4 was immaculate. Clean interior and powerful automatic gearbox.',
      },
    ]);

    console.log(`✅ Auto-seeded ${createdVehicles.length} vehicles successfully!`);
  } catch (error) {
    console.error('Auto-seed error:', error);
  }
};
